/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSosRouteImport } from './routes/_app/sos'
import { Route as AppReceitasRouteImport } from './routes/_app/receitas'
import { Route as AppBebeRouteImport } from './routes/_app/bebe'
import { Route as AppReceitasIdRouteImport } from './routes/_app/receitas.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppBebeRoute = AppBebeRouteImport.update({
  id: '/bebe',
  path: '/bebe',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasIdRoute = AppReceitasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReceitasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/bebe': typeof AppBebeRoute
  '/receitas': typeof AppReceitasRouteWithChildren
  '/sos': typeof AppSosRoute
  '/receitas/$id': typeof AppReceitasIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/bebe': typeof AppBebeRoute
  '/receitas': typeof AppReceitasRouteWithChildren
  '/sos': typeof AppSosRoute
  '/': typeof AppIndexRoute
  '/receitas/$id': typeof AppReceitasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/bebe': typeof AppBebeRoute
  '/_app/receitas': typeof AppReceitasRouteWithChildren
  '/_app/sos': typeof AppSosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/receitas/$id': typeof AppReceitasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/bebe'
    | '/receitas'
    | '/sos'
    | '/receitas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/onboarding' | '/bebe' | '/receitas' | '/sos' | '/' | '/receitas/$id'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/bebe'
    | '/_app/receitas'
    | '/_app/sos'
    | '/_app/'
    | '/_app/receitas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sos': {
      id: '/_app/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas': {
      id: '/_app/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bebe': {
      id: '/_app/bebe'
      path: '/bebe'
      fullPath: '/bebe'
      preLoaderRoute: typeof AppBebeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas/$id': {
      id: '/_app/receitas/$id'
      path: '/$id'
      fullPath: '/receitas/$id'
      preLoaderRoute: typeof AppReceitasIdRouteImport
      parentRoute: typeof AppReceitasRoute
    }
  }
}

interface AppReceitasRouteChildren {
  AppReceitasIdRoute: typeof AppReceitasIdRoute
}

const AppReceitasRouteChildren: AppReceitasRouteChildren = {
  AppReceitasIdRoute: AppReceitasIdRoute,
}

const AppReceitasRouteWithChildren = AppReceitasRoute._addFileChildren(
  AppReceitasRouteChildren,
)

interface AppRouteChildren {
  AppBebeRoute: typeof AppBebeRoute
  AppReceitasRoute: typeof AppReceitasRouteWithChildren
  AppSosRoute: typeof AppSosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBebeRoute: AppBebeRoute,
  AppReceitasRoute: AppReceitasRouteWithChildren,
  AppSosRoute: AppSosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
